wq: openssl support
cooperative-computing-lab/cctools pull request #2733
Opened 2021-11-09 19:09 UTC by btovar

(Issue #2635)

@dthain: If it looks ok, I can update the manual and man pages.

Still need to add the options to makeflow when using Work Queue, but I think we can do that in another pr.

I tried to make it so that current code does not need any change. Only a handful of functions from link.c had to be wrapped with openssl code.

For the catalog, the managers report "ssl: true when appropriate.  A worker can then initiate a TLS connection. When using HOST PORT, a worker needs the --ssl flag.  The --ssl flag is always needed for `work_queue_status HOST PORT` when the manager to query is using ssl.

2021-11-09 19:17 UTC, btovar commented
Seems like I need to update the docker images to include libssl-dev

2021-11-11 20:46 UTC, dthain requested changes
Yes, I think this is really well done, with the changes being quite compact.
A few naming items in the middle, but the approach looks good overall.

2021-11-11 20:46 UTC, dthain commented on dttools/src/link.c
> +int _ssl_errors_cb(const char *str, size_t len, void *use_warn) {
static functions?

2021-11-11 20:46 UTC, dthain commented on dttools/src/link.c
> +ssize_t _read(struct link *link, char *data, size_t count) {
Name of _read likely conflicts with libc symbols.

2021-11-11 20:46 UTC, dthain commented on dttools/src/link.c
> +ssize_t _write(struct link *link, const char *data, size_t count) {
Ibid

2021-11-12 19:56 UTC, btovar commented
Build fails because TLS_client_method() in more recent versions of openssl. Adding a config check to select the correct openssl call...

2021-11-15 17:38 UTC, btovar commented
@dthain, this is ready to merge from my side. You may want to take a look at the note in the wq manual. 
https://github.com/cooperative-computing-lab/cctools/pull/2733/commits/33db544c64b3f1231f5c754a926074eeba408353

2021-11-15 17:59 UTC, dthain commented on doc/manuals/work_queue/index.md
At the beginning of the section, place the note that, by default, no authentication is done,
and so you can do SSL, password, or both.

2021-11-15 18:00 UTC, dthain commented on doc/manuals/work_queue/index.md
> +
Explain a little bit more here that this is self-signed, with the usual proviso...

2021-11-15 18:00 UTC, dthain commented on doc/manuals/work_queue/index.md
>  By default, Work Queue does **not** perform any authentication, so any workers
Move this paragraph above...

2021-11-15 18:01 UTC, dthain commented on doc/manuals/work_queue/index.md
Also a bit that SSL provides manager-to-worker authentication, while password gives you worker-to-manager auth.

2021-11-15 18:02 UTC, dthain commented on doc/manuals/work_queue/index.md
Also, that reminds me that the warning message emitted by the manager should now mention using either password or ssl.

2021-11-15 18:02 UTC, dthain commented on doc/manuals/work_queue/index.md
> +#### TLS (SSL) support
Call this SSL consistently, since that's how we name the options and code...

2021-11-16 14:59 UTC, merged