Catalog: Add HTTPS/SSL query capability.  (WIP)
cooperative-computing-lab/cctools pull request #2763
Opened 2021-11-23 20:06 UTC by dthain

First pass, as yet untested.

2021-11-29 17:21 UTC, dthain commented
Doesn't quite work yet b/c the existing code breaks the `link` abstraction by getting the underlying fd with `link_fd` and then creating a stdio stream, which breaks the SSL abstraction.  What we need to do here is create a `link_printf` that sits on top of `link_write`.

2021-11-29 21:54 UTC, dthain commented
Catalog now serves up results via ssl correctly.

2021-11-30 15:50 UTC, btovar requested changes

2021-11-30 15:50 UTC, btovar commented on work_queue/src/work_queue.c
> +		if(q->ssl_cert) free(q->ssl_cert);
No need of `if`.  `free(NULL)` does nothing.

2021-11-30 15:50 UTC, btovar commented on dttools/src/link.c
> -		link->ctx = _create_ssl_context(/* is client */ 1);
Drop the argument from `_create_ssl_context`, and use `TLS_method()` or `SSLv23_method()` as appropriate.

2021-11-30 20:45 UTC, dthain commented
Catalog is working now, WQ fixed up slightly to deal with changes to link.
Remaining piece here is that deltadb needs the capability to write to a link as well as a stream.
Also need to look at the performance impact of link_printf versus printf.
The former does a single link_write for each link_printf, whereas the latter is buffering blocks.
We may need to add an output buffer for link_printf.

2021-12-01 14:55 UTC, btovar requested changes

2021-12-01 15:01 UTC, btovar commented
The changes to `link_accept` also fix a current bug with ssl in osx and conda where SSL_accept fails with a SSL_SYSCALL_ERROR.  Thus, I would like to add this pr to 7.4.0.

2021-12-01 15:47 UTC, dthain commented
I think this branch needs more cooking -- I'm leery of updating the catalog server too aggressively.  Are you willing to backport the ssl changes?  I think it's just a matter of link.c and work_queue.c

2021-12-01 16:21 UTC, btovar commented
Yes, I was thinking of backporting those changes.

re nonblocking: It is a possibility, but I did try changing the SSL_accept wrapper to also retry on want_read/write, but the error is fatal for the connection.

2021-12-07 18:51 UTC, dthain commented
This is stuck at the moment b/c the OSX build does not detect the presence of openssl in configure.
This is because OSX no longer puts dynamic libraries in /usr/lib, so configure cannot find them.
Yep, really:

_New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)_

https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes

So, we need to figure out how to adjust configure appropriately without turning the whole thing inside out...

2021-12-07 19:09 UTC, btovar commented
Great.

We'll need to support both methods (path and dlopen), as we need the path method for conda.

2021-12-07 19:36 UTC, dthain commented
Ah, are you telling me that when we install on osx via conda, the libraries are found in the usual way?

2021-12-07 19:40 UTC, btovar commented
Yes, openssl comes from conda.

2021-12-07 19:55 UTC, btovar commented
Actually, looking around, dlopen may not help us much as the openssl headers may not be there. People seem to recommend installing openssl from brew, etc.

2021-12-08 16:01 UTC, dthain commented
Worked around this by writing the SSL test to depend up on CCTOOLS_OPENSSL_AVAILABLE.
I think we are ok as long as Conda is the preferred installation method.

2021-12-13 16:05 UTC, merged