Add options in makeflow_graph_log to support specifying paths for gnuplot and convert
cooperative-computing-lab/cctools pull request #2864
Opened 2022-05-24 18:57 UTC by sghuang19

```
makeflow_graph_log [options] <makeflowlog> <imagefile>
```

Use `-g` to specify path to `gnuplot`, `-c` to specify path to `convert`. `PATH` is used by default.

2022-05-24 19:00 UTC, sghuang19 commented
#2863

2022-05-25 12:12 UTC, btovar requested changes

2022-05-25 12:12 UTC, btovar commented on makeflow/src/makeflow_graph_log
> +	  echo "$0: could not find $prog in the PATH variable or in the specified path"
Let's change this whole if to:
```sh
if ! which $prog >& /dev/null
then
   echo ...
  exit 1
fi
```

2022-05-25 12:12 UTC, btovar commented on makeflow/src/makeflow_graph_log
> +		gnuplot=$1
"$1"

2022-05-25 12:12 UTC, btovar commented on makeflow/src/makeflow_graph_log
> +		convert=$1
"$1"

2022-05-25 13:33 UTC, btovar requested changes

2022-05-26 15:08 UTC, merged