wq: add input and output lines in the transaction log
cooperative-computing-lab/cctools pull request #2879
Opened 2022-05-31 19:45 UTC by sghuang19

I'm not sure how to test it, but the codes are done.

2022-05-31 19:45 UTC, sghuang19 commented
#2879

2022-06-02 17:46 UTC, btovar requested changes

2022-06-02 17:46 UTC, btovar commented on work_queue/src/work_queue.c
> +        write_transaction_transfer(q, w, t, total_bytes, sum_time, f->remote_name, 0);
Instead of 0, let's use:  `WORK_QUEUE_OUTPUT`

2022-06-02 17:46 UTC, btovar commented on work_queue/src/work_queue.c
> +		write_transaction_transfer(q, w, t, total_bytes, elapsed_time, f->remote_name, 1);
As above, change 1 to `WORK_QUEUE_INPUT`

2022-06-02 17:46 UTC, btovar commented on work_queue/src/work_queue.c
> +	if (type)
Use braces for both the `if` and `else`, even it it is only one statement.
Also, now use
```
if(type == WORK_QUEUE_INPUT) {  
    ...
```

2022-06-02 17:46 UTC, btovar commented on work_queue/src/work_queue.c
> +static void write_transaction_transfer(struct work_queue *q, struct work_queue_worker *w, struct work_queue_task *t, size_t sizeinmb, int walltime, char* filename, int type){
Note that size and walltime come in bytes, and microseconds, respectively.  I'd suggest changing the parameters to:
```C
..., size_t size_in_bytes, int time_in_usecs, work_queue_file_type_t type) {
```

and convert to MB and seconds as needed. Use "%f" when printing the numbers below.

2022-06-03 12:18 UTC, btovar commented on work_queue/src/work_queue.c
> +static void write_transaction_transfer(struct work_queue *q, struct work_queue_worker *w, struct work_queue_task *t, size_t sizeinmb, int walltime, char* filename, int type){
For memory, divide by `((double) MEGABYTE)`.  For time, divide by `((double) USECOND)`, and use "%f" in buffer_print for both.

2022-06-03 15:12 UTC, btovar approved these changes

2022-06-03 15:12 UTC, merged