Option to specify RemoteTask arguments by keyword, position, dictionary, or position
cooperative-computing-lab/cctools pull request #2883
Opened 2022-06-03 17:13 UTC by David-Simonetti-ND

When creating a RemoteTask, one can specify arguments by keyword as before, but now there is support for positional arguments and passing in a dictionary containing keyword arguments (pass in the dictionary as work_queue_argument_dict). The user can also mix and match these arguments, passing some arguments by keyword and some by position.

2022-06-07 16:48 UTC, btovar requested changes

2022-06-07 16:48 UTC, btovar commented on work_queue/src/bindings/python3/work_queue.binding.py
> +    def __init__(self, fn, coprocess, *args, **kwargs):
What do you think of adding a `specify_exec_method()` to `RemoteTask`?   I don't like that the kwarg `exec_method` gets mixed with the args to the function.
Such method may also simplify the code needed to remove the `exec_method` key from the kwarg dict.

2022-06-08 19:56 UTC, David-Simonetti-ND commented
Changed RemoteTask so that the event is only transferred to infile once the task is submitted to the queue, because otherwise the event would be turned into an infile once the task was created and would not allow any changes to be made (since the file was already created). This allows two new functions, specify_argument_dictionary and specify_exec_method which allow the user to set a dictionary as argument and change the exec_method on the network side. The exec_method is now no longer passed with the kwargs of the function.

```
t = wq.RemoteTask("my_sum", "my_coprocess_example")
t.specify_argument_dictionary(argument_dict={"a":5, "b":5})
t.specify_exec_method("fork")
queue.submit(t)
t = wq.RemoteTask("my_sum", "my_coprocess_example", a=2, b=3)
queue.submit(t)
```

2022-06-09 17:29 UTC, btovar requested changes

2022-06-09 17:29 UTC, btovar commented on work_queue/src/bindings/python3/work_queue.binding.py
> +        if "_event" in task.__dict__:
Instead use something like: `if isinstance(task, RemoteTask):`

2022-06-09 17:29 UTC, btovar commented on work_queue/src/bindings/python3/work_queue.binding.py
> +        self._event["work_queue_kwargs"] = kwargs
Rename these ones to  `fn_args` and `fn_kwargs`. They relate to the function, not wq.

2022-06-09 17:29 UTC, btovar commented on work_queue/src/bindings/python3/work_queue.binding.py
> +    def specify_argument_dictionary(self, *args, argument_dict=None):
`specify_fn_args(args=None, kwargs=None)` as it does more than the dict. Use like: `specify_fn_args([1,2,3], {"a": 2})`

2022-06-09 18:33 UTC, btovar commented
Ready to merge?

2022-06-09 18:34 UTC, David-Simonetti-ND commented
Yup! Ready to merge

2022-06-09 18:39 UTC, merged