wq: work_queue_graph_workers documentation
cooperative-computing-lab/cctools pull request #2903
Opened 2022-06-27 14:18 UTC by sghuang19

Some documentations for the viz tool.

2022-06-27 18:52 UTC, sghuang19 commented
These two are all the documentation locations I found so far.

2022-06-28 12:54 UTC, btovar requested changes

2022-06-28 12:54 UTC, btovar commented on doc/manuals/work_queue/index.md
> +of file transfer time on overall performance. See `man
Here lets have a link to man url. (See how it is done in `doc/manuals/manpages`  for https://cctools.readthedocs.io/en/stable/man_pages.)

2022-06-28 14:26 UTC, btovar requested changes

2022-06-28 14:26 UTC, btovar commented on doc/manuals/work_queue/index.md
> +[work_queue_graph_workers(1)](work_queue_graph_workers.md) for detailed
I think you want:
```
[work_queue_graph_workers](../man_pages/work_queue_graphs_workers.md)
```

2022-06-28 14:58 UTC, btovar commented
We are hesitant to update the logs, as it may break tools that process the files downstream...

2022-06-28 15:18 UTC, sghuang19 commented
But the updates have already been merged. Besides, what we did is just add a line for `TRANSFER`, it shouldn't be conflicting with existing scripts.

2022-06-28 16:00 UTC, btovar requested changes

2022-06-28 16:00 UTC, btovar commented on doc/manuals/work_queue/index.md
> +# time manager_pid MANAGER START|END
Please cleanup this commit, so that only line 1796 is the one that changes.

2022-06-28 16:01 UTC, merged