Updates Poncho and doc to reflect Conda's specification format
cooperative-computing-lab/cctools pull request #2956
Opened 2022-08-19 16:53 UTC by BarrySlyDelgado

This addresses #2949. the key "packages" is changed to "dependencies". pip packages are under "dependencies" as well within their own dict. The doc manual has been updated to reflect this change.

2022-08-19 16:54 UTC, dthain commented
Will this break existing tools (Parsl, Coffea, TopEFT) that are already using Poncho?

2022-08-19 17:00 UTC, BarrySlyDelgado commented
@dthain This would affect tools that use  `poncho_package_create`  Already created specifications would have to be updated to the new format to use poncho_package_create. So, I believe that topEFT would have to be modified.

2022-08-19 18:43 UTC, dthain commented
So we can't just break our most important customers.
And we must consider the case that multiple versions will exist simultaneously.
The way to proceed here is to permit the new keywords while retaining backwards compatibility with the old ones.
Then, update Parsl/Coffea to use the new keywords.
Finally, remove support for the old keywords once everyone has transitioned.

2022-08-19 18:51 UTC, BarrySlyDelgado commented
I will change it to allow both formats for the specifications.

2022-08-22 17:12 UTC, BarrySlyDelgado commented
Poncho_package_create now accepts both specification formats. All existing tools that use Poncho should still operate correctly.

2022-08-22 17:16 UTC, btovar requested changes

2022-08-22 17:16 UTC, btovar commented on doc/manuals/poncho/index.md
> +poncho_package_run -e package.tar.gz python example.py
Let's keep the -- here, e.g.: `poncho_package_run -e package.tar.gz -- python example.py`

2022-08-22 17:29 UTC, btovar approved these changes

2022-08-22 17:29 UTC, merged