Translated taskvine examples to Python
cooperative-computing-lab/cctools pull request #3044
Opened 2022-10-31 13:41 UTC by JosephDuggan7

2022-11-02 14:16 UTC, btovar requested changes

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example.py
> +      t.add_input_file(gzip_path, "gzip", flags=VINE_UNPACK, cache=True)
I don't think you need any extra flags here. In all your changes in this example, I don't see any need to use VINE_UNPACK.

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_blast.py
> +query_string = ">P01013 GENE X PROTEIN (OVALBUMIN-RELATED)\n\
Here lets' use multiline strings, as:

```python
query_string = """>P01013 GENE X PROTEIN (OVALBUMIN-RELATED)
QIKDLLVSSSTDLDTTLVLVNAIYFKGMWKTAFNAEDTREMPFHVTKQESKPVQMMCMNNSFNVATLPAE
...
"""

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_blast.py
> +BLAST_URL = "https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.13.0+-x64-linux.tar.gz"
lower case these ones, so it looks more pythonic.

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_blast.py
> +        t.add_input_buffer(query_string,"query.file", flags=VINE_NOCACHE)
In these ones lets do:  `cache=False`,  or  `cache=True, flags=VINE_UNPACK`.  We are removing that flags arg in the short future.

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_blast.py
> +    del m
Not needed in python.

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_blast.py
> +    sys.exit(0)
Not needed.

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_blast.py
> +from taskvine import *
Here let's do:
```python
import taskvine as vine
```
and modify the rest of the lines as needed. (In all the examples.)

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_gutenberg.py
> +            t.add_input_file("vine_example_gutenberg_script.sh", "vine_example_gutenberg_script.sh", flags=VINE_CACHE)
cache = True instead of flags.

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_gutenberg.py
> +    del m
del m and sys.exit(0) not needed.

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_gutenberg.py
> +            del t
Not needed.

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_blast.py
> +            del t
del t and del m in all the examples are not needed. In fact they may lead to an error.

2022-11-02 14:16 UTC, btovar commented on taskvine/src/examples/vine_example_watch.py
> +from taskvine import *
Modify as the examples above.

2022-11-03 01:47 UTC, JosephDuggan7 commented
Made requested changes

2022-11-03 11:49 UTC, btovar requested changes

2022-11-03 11:49 UTC, btovar commented on taskvine/src/examples/vine_example_blast.py
> +		QIKDLLVSSSTDLDTTLVLVNAIYFKGMWKTAFNAEDTREMPFHVTKQESKPVQMMCMNNSFNVATLPAE
You want to remove the leading spaces here, otherwise they become part of the query string.

2022-11-03 11:49 UTC, btovar commented on taskvine/src/examples/vine_example.py
> +      q = vine.Manager(port = vine.VINE_DEFAULT_PORT)
In all the examples, let's use:  `q = vine.Manager()`, as the default port is used when no arguments are given, and all caps constants look unpythonic.

2022-11-03 11:49 UTC, btovar commented on taskvine/src/examples/vine_example.py
>              None
Here let's use `pass`, rather than `None`

2022-11-03 11:49 UTC, btovar commented on taskvine/src/examples/vine_example_blast.py
> +            if r==vine.VINE_RESULT_SUCCESS:
`r == vine.VINE_RESULT_SUCCESS`
In general, add spaces to `x == y` or `x = y`.

2022-11-03 21:33 UTC, JosephDuggan7 commented
Made changes

2022-11-04 15:32 UTC, merged