Updated python abstractions and created examples
cooperative-computing-lab/cctools pull request #3073
Opened 2022-12-10 00:58 UTC by JosephDuggan7

2023-01-11 15:21 UTC, dthain commented
@JosephDuggan7 the examples here look nice, but the PR contains a number of binary objects and log files that shouldn't be checked in, please remove them.

2023-01-11 15:22 UTC, dthain requested changes
Please remove the unneeded files from the PR.

2023-01-18 22:10 UTC, JosephDuggan7 commented
Removed unneeded files

2023-02-01 13:00 UTC, btovar requested changes

2023-02-01 13:00 UTC, btovar commented on taskvine/src/examples/vine_example_pair.py
> +import taskvine as vine
This example fails with:
```
TypeError: 'PythonTaskNoResult' object is not iterable
```

2023-02-01 13:00 UTC, btovar commented on taskvine/src/bindings/python3/taskvine.binding.py
> +                    print(t.output)
debugging statement?

2023-02-02 04:11 UTC, JosephDuggan7 commented
Removed print statement, however I am not encountering any errors with that example

2023-02-02 12:24 UTC, merged