Vine Plotting Tool vine_plot_txn_log
cooperative-computing-lab/cctools pull request #3107
Opened 2023-02-08 18:39 UTC by BarrySlyDelgado

2023-02-08 18:42 UTC, btovar requested changes

2023-02-08 18:42 UTC, btovar commented on taskvine/src/tools/vine_plot_txn_log.py
> +from collections import Counter
First line should be: 
```sh
#! /usr/bin/env python
```

2023-02-08 19:30 UTC, btovar requested changes

2023-02-08 19:30 UTC, btovar commented on taskvine/src/tools/vine_plot_txn_log.py
> +import matplotlib.pyplot as plt
Also, add a copyright notice.

2023-02-08 21:17 UTC, dthain commented
`vine_graph_txn_log` for consistency with other tools.

2023-02-08 23:42 UTC, btovar approved these changes

2023-02-09 12:24 UTC, btovar requested changes

2023-02-09 12:24 UTC, btovar commented on taskvine/src/tools/vine_plot_txn_log
> +
Let's add this style for accessibility:

`plt.style.use('tableau-colorblind10')`

2023-02-10 12:45 UTC, btovar approved these changes

2023-02-10 12:47 UTC, btovar commented
Ready to be merged?

2023-02-10 14:54 UTC, BarrySlyDelgado commented
Its ready.

2023-02-10 15:19 UTC, merged