Vine: Serverless sandbox fixed
cooperative-computing-lab/cctools pull request #3166
Opened 2023-02-27 21:30 UTC by mcarbona1

This is the fix for the serverless sandbox issues that caused output file transfers to fail. By sending the sandbox to the coprocess, the duty can then change directory before doing anything else. This makes sure the work is done in the proper directory and that the worker knows where to look when it's time to transfer the files back.

2023-02-28 12:20 UTC, btovar reviewed
The biggest issue is that threads do not have their own working directory. Thus, this modification won't work if more than one function runs concurrently in the coprocess. Thus, since only one function can be executed, this effectively makes the "thread" method the same as the "direct" method. Using os.chdir in a thread will make some debugging horror stories.

I suggest getting rid of the "thread" method. If more than one function has to run concurrently, either use the fork method, or have the worker spawn multiple coprocesses.

2023-02-28 12:33 UTC, btovar commented
Also, I'm not sure that the coprocess won't get confused when using "thread" and "direct" after the os.chdir().  It might be that the mounts given to the coprocess will also need to be mounted in the task sandboxes.  Along these lines, at the end of the function execution the sandbox is deleted, and the current working directory of the coprocess is gone.

2023-02-28 13:35 UTC, dthain commented
Agreed -- the sandbox directory is fundamental to the taskvine abstractions.
And that seems to be incompatible with the threads model.


On Tue, Feb 28, 2023 at 7:33 AM Benjamin Tovar ***@***.***>
wrote:

> Also, I'm not sure that the coprocess won't get confused when using
> "thread" and "direct" after the os.chdir(). It might be that the mounts
> given to the coprocess will also need to be mounted in the task sandboxes.
> Along these lines, at the end of the function execution the sandbox is
> deleted, and the current working directory of the coprocess is gone.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cooperative-computing-lab/cctools/pull/3166#issuecomment-1448104672>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAVADETC6WYB7WV2N6N2EFDWZXWDBANCNFSM6AAAAAAVJ5R37I>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-02-28 20:50 UTC, David-Simonetti-ND reviewed
I agree, getting rid of the thread execution method makes sense. As Python only allows one thread to run at any given time, running multiple coprocesses on one worker would be the way to achieve concurrency.

2023-02-28 21:30 UTC, mcarbona1 commented
Ok, I've removed the thread options from the package_serverize.py code and the taskvine bindings so it no longer will accept the thread option as well as edited some comments to remove the mention of threads. As far as I can tell there is no mention of serverless threading in the manual yet so I don't think anything has to change there.

2023-03-01 14:55 UTC, btovar requested changes

2023-03-01 14:55 UTC, btovar commented on poncho/src/poncho/package_serverize.py
> +                        os.chdir(sandbox)
Here you want to re-establish the previous working directory after the function is execute, regardless of any error. Please look at  the  `try: except: finally:` statements.

For the fork one this is not needed, as the process that switch working directory exits just after execution.

2023-03-06 20:57 UTC, mcarbona1 commented
Ok, I think this is pretty much what we discussed @btovar, let me know if there are any other changes you want me to make!

2023-03-30 23:10 UTC, btovar commented
Closing because of conflicts. Re-doing one commit.

2023-03-30 23:10 UTC, closed without merging