WQ:  Attempt scheduling a fixed number of tasks to expedite retrievals
cooperative-computing-lab/cctools pull request #3373
Opened 2023-06-06 15:10 UTC by colinthomas-z80

2023-06-07 13:26 UTC, dthain commented
Please rebase on master for a clean build.

2023-06-07 14:34 UTC, dthain requested changes

2023-06-07 14:34 UTC, dthain commented on work_queue/src/work_queue.c
> +	} else if(!strcmp(name, "attempt-schedule-depth")) {
Make sure to add this new tuning parameter to the docs in `taskvine.h`

2023-06-07 14:34 UTC, dthain commented on work_queue/src/work_queue.c
> -	while( (t = list_next_item(q->ready_list))) {
I'm a little uncomfortable with the implied free/malloc that comes from pop/push every time we consider one item.  Also, the multiple exit points that all must call `list_push_tail` looks like a maintenance hazard.

What would you think of introducing a new call `list_rotate` that moved the head item to the tail (without free/malloc) returning its value?

So then you would have this:
```
while( t= list_rotate(q->ready_list) ) {
    // check various conditions and return if needed

   // finally
   list_pop_tail
   commit_task_to_worker
}
```

2023-06-08 19:16 UTC, dthain approved these changes

2023-06-08 19:26 UTC, colinthomas-z80 commented
@dthain yes!

2023-06-08 19:27 UTC, merged