Asynchronous worker transfers (WIP)
cooperative-computing-lab/cctools pull request #3391
Opened 2023-07-07 14:12 UTC by BarrySlyDelgado

Tested with 1 worker so far.
- vine_sandbox_ensure checks if all files are ready for a process. Returns 1 if all files are present, Returns 0 on failure and Returns -1 when a transfer is still running.
- vine_cache_wait checks to see if a transfer process has completed.
- vine_cache_ensure forks if a file is not present. If the file is a mini task I think we should first ensure each of its dependencies are present.

2023-07-07 15:48 UTC, dthain reviewed
Yes, this is the right idea.  However, instead of using 1/0/-1, make an enumeration that describes complete/failed/running so that is clearer for the reader to understand what's happening.

You are correct that ensure() called on a mini-task should check all of its inputs.

2023-07-24 19:26 UTC, dthain requested changes

2023-07-24 19:26 UTC, dthain commented on taskvine/src/worker/vine_cache.c
> +					f->complete = -1;
Another case where a variable looks like a boolean, but isn't.
Make this an enumeration that explains what all the possible values mean.

2023-07-24 19:26 UTC, dthain commented on taskvine/src/worker/vine_process.c
> +
Don't duplicate the `string_format` calls here.
Instead do something like this:

```
const char *type = mini_task ? "m" : "t";
```

Then just use those strings when calling string_format.

2023-07-24 19:26 UTC, dthain commented on taskvine/src/worker/vine_sandbox.c
> +int vine_sandbox_ensure(struct vine_process *p, struct vine_cache *cache, struct link *manager)
This function currently returns a boolean, presumably true if all the files are present.
But I think there are three possibilities:
1 - All files are downloaded and present.  The task should run now.
2 - Some files have not been downloaded yet.  The task should not run yet.
3 - One or more files failed to download.  The task should be returned as a failure.

So this function needs a better return value that is handled properly where it is called.

2023-07-24 19:26 UTC, dthain commented on taskvine/src/worker/vine_sandbox.c
> +int vine_sandbox_ensure(struct vine_process *p, struct vine_cache *cache, struct link *manager)
Or possibly case 3 should allow the task to proceed to execution, and then fail in `vine_sandbox_stagein`.

2023-07-25 16:59 UTC, dthain requested changes

2023-07-25 16:59 UTC, dthain commented on taskvine/src/worker/vine_cache.h
> +	VINE_FILE_UNKNOWN,
This is looking much better.  However, there is likely to be some confusion of names b/c we already have a number of `VINE_FILE_X` symbols.  Suggest that you call the field `f->status` and the values `VINE_FILE_STATUS_X`

2023-07-25 16:59 UTC, dthain commented on taskvine/src/worker/vine_cache.h
> +typedef enum {
Seems like this is duplicating `vine_file_status_t` you could just re-use that type.

2023-07-27 14:10 UTC, dthain commented
Barry, per our discussion today, only the transfer should happen in the child process.  The manipulation of data structures (particularly on completion) should happen in the parent process.  (Some in `vine_cache_wait`). Also, make the child process a distinct function, so it's very clear where the limited action takes place.

2023-07-28 16:45 UTC, dthain requested changes
Almost there!

2023-07-28 16:45 UTC, dthain commented on taskvine/src/worker/vine_cache.c
> -struct cache_file {
The definition of `cache_file` should stay inside of `vine_cache` b/c we don't want other modules manipulating it outside of the API.

2023-07-28 16:45 UTC, dthain commented on taskvine/src/worker/vine_cache.c
> +			if(result !=0 && f->type==VINE_CACHE_MINI_TASK){
This seems like a strange place to put this, shouldn't it be part of the `result>0` clause below with the rest of the success case?

2023-07-28 16:45 UTC, dthain commented on taskvine/src/worker/vine_cache.c
>  	}
Nothing is done with the error message here, at the very least send it to the debug stream.

2023-07-28 17:10 UTC, dthain commented
Ok, this is going to need some serious testing.  What's the biggest workflow that you have run with this?

2023-07-28 19:26 UTC, BarrySlyDelgado commented
I've ran it with `vine_example_future_matrix` using 10 workers each with 4 cores the workflow had 512 tasks using SGE. temp files should be transferred asynchronously. I also done it with the blast example but only with one worker which includes minitasks and url transfers.

2023-07-28 19:50 UTC, dthain commented
Go bigger yet!

2023-07-31 17:27 UTC, dthain approved these changes

2023-08-07 14:16 UTC, dthain requested changes

2023-08-07 14:16 UTC, dthain commented on taskvine/src/worker/vine_cache.c
> +int vine_cache_wait(struct vine_cache *c, struct link *manager)
Please factor this function into several smaller functions that:
- iterate over the table
- process one entry
- evaluate the exit status
- extract the outputs

I think that will make the behavior more transparently clear.

2023-08-07 14:16 UTC, dthain commented on taskvine/src/worker/vine_cache.c
> +	/* File is already present in the cache. */
As a general rule, when you are examining the states of an enumeration, use a `switch` and address all of the cases.
This is a defensive measure that will make it easier to maintain the code if/when the enumeration adds or removes cases.

2023-08-10 16:31 UTC, dthain commented on taskvine/src/worker/vine_cache.c
> +		if(f->type==VINE_CACHE_TRANSFER) debug(D_VINE,"cache: transferring %s to %s",f->source,cachename);
Again, use a switch.

2023-08-10 16:31 UTC, dthain commented on taskvine/src/worker/vine_cache.c
> +	char *cache_path = vine_cache_full_path(c,cachename);
Memory leak

2023-08-11 16:23 UTC, BarrySlyDelgado commented
I think I have to remove the `stagein` check included by PR #3450 since in this PR we are already checking if a minitask has its inputs in vine_cache_ensure and won't proceed with task execution if it doesn't. The `stagein` call will in the `process_execute_and_wait function` may be causing the tests to fail as it would be trying to link into the task sandbox twice?

2023-08-11 16:29 UTC, dthain commented
Well, be careful to mind the general principle:

`vine_sandbox_stagein` creates the sandbox and links the inputs to their proper places.

It has to be called somewhere.
 
And wherever it is called, the results must be checked.

2023-08-14 18:23 UTC, merged