Vine Futures Executor
cooperative-computing-lab/cctools pull request #3403
Opened 2023-07-14 13:35 UTC by BarrySlyDelgado

2023-07-14 14:59 UTC, dthain reviewed
This looks like it's on the right track.  Still needs some documentation, an example program, and a test case to be complete.

2023-07-14 14:59 UTC, dthain commented on taskvine/src/manager/vine_manager.c
>  				/* XXX we cannot tell between temp that was never run, and one that failed! */
This comment is no longer true!

2023-07-14 14:59 UTC, dthain commented on taskvine/src/bindings/python3/ndcctools/taskvine/manager.py
> +
Perhaps the Executor should be in a separate module?

2023-07-24 19:12 UTC, dthain approved these changes

2023-07-24 19:12 UTC, dthain commented on taskvine/src/examples/vine_example_future_matrix.py
> +print('Generated Matricies...')
Matrices

2023-07-24 19:12 UTC, dthain commented on doc/manuals/taskvine/index.md
> +of pythons concurrent futures executor. A function along with its
Python's

2023-07-24 19:12 UTC, dthain commented on taskvine/src/examples/vine_example_future_matrix.py
> +# It performs matrix multiplications on multiple matricies
throughout: matrices

2023-07-24 19:12 UTC, dthain commented on taskvine/src/examples/vine_example_future_matrix.py
> +executor.set("memory", 8000)
This is a notable bit here: you are setting properties for all future tasks.  Highlight with some commentary.

2023-07-24 19:12 UTC, dthain commented on taskvine/src/examples/vine_example_future_matrix.py
> +env_spec = {"conda": {"channels": ["conda-forge"],"packages": ["python","pip","conda","conda-pack","cloudpickle"]}}
Explain this too

2023-07-24 19:27 UTC, dthain requested changes
Whoops, I meant to select 'request changes' before, see comments from prior review.

2023-07-26 18:22 UTC, dthain approved these changes

2023-07-26 18:24 UTC, dthain commented
RTM?

2023-07-26 18:24 UTC, BarrySlyDelgado commented
Yes.

2023-07-26 18:25 UTC, merged