Vine: Partial fix of resources for serverless feature.
cooperative-computing-lab/cctools pull request #3477
Opened 2023-08-25 18:41 UTC by tphung3

This PR made the following changes:
- Set default resources for library tasks so these tasks will have resources accounted for. The values are arbitrary and need further consideration.
- Remove max_proportion adjustment in `vine_manager_choose_resources_for_task`. This code assumes all tasks have the same resource box and thus tries to round resources. This is not true when library task uses few resources (e.g., 1 core) and function call tasks use arbitrary resources.
- Add check for library tasks when sending them to workers. This check is needed in case worker doesn't have available resources.
- Log library sending operation appropriately.
- Make `check_worker_against_task` available to be used in `vine_manager.c`.
- Fix resources for worker and tasks in serverless test script.

Warning: this setup won't work if function calls don't specify the right amount of resources. Also current implementation only allows 1 function call per library. 

Todo: clean design of resources for serverless.

2023-08-25 19:51 UTC, dthain requested changes
Glad you got it working!
Two little things to fix.

2023-08-25 19:51 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> -			// adjust max_proportion so that an integer number of tasks fit the
Hmm, I think this is an important step for normal tasks.
Maybe make this conditional on `!t->needs_library` so that it doesn't apply to functions?

2023-08-25 19:51 UTC, dthain commented on taskvine/src/bindings/python3/ndcctools/taskvine/task.py
> +        # Set some default resources to a library task so it doesn't consume whole worker.
Let's not set default resources in `task.py`, I think it's going to be very easy to forget that they are here.
You are already setting them in the application code anyway.

2023-08-28 16:52 UTC, dthain commented
ping?

2023-08-28 19:03 UTC, tphung3 commented
This PR is RTM.

2023-08-28 19:07 UTC, dthain approved these changes

2023-08-28 19:47 UTC, merged