Update README.md
cooperative-computing-lab/cctools pull request #3525
Opened 2023-10-01 04:07 UTC by thieber22

## Proposed changes

Updated README.md in repo root to include dependency installation via environment.yml

## Post-change actions

Put an 'x' in the boxes that describe post-change actions that you have done.
The more 'x' ticked, the faster your changes are accepted by maintainers.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [X] Manual Update     Did you update the manual to reflect your changes, if appropriate? This action should be done after your changes are approved but not merged.
- [ ] Type Labels       Select github labels for the type of this change: bug, enhancement, etc.
- [ ] Product Labels    Select github labels for the product affected: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

## Additional comments
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to start the ball rolling.

2023-10-02 12:51 UTC, dthain requested changes
This isn't quite right: the "Quick Install" section is correct as-is, because it explains how to install the binaries without the source. You want to modify the section below, so that it shows how to install the build dependencies and then build from source.

2023-10-09 20:31 UTC, dthain commented
Ping?

2023-10-10 16:04 UTC, thieber22 commented
Changed README to include instructions for cloning repo and installing dependencies from environment.yml

2023-10-11 17:30 UTC, dthain approved these changes

2023-10-11 17:30 UTC, merged