TaskVine: Fix problem where function calls print to stdout of the vine_worker process
cooperative-computing-lab/cctools pull request #3585
Opened 2023-12-07 20:50 UTC by tphung3

## Proposed changes

Before, if a function call prints anything to stdout, then it is routed to the vine_worker process' stdout. This fixes that and make the library task have the same stdin/out/err setup as the standard task.

## Post-change actions

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Did you update the manual to reflect your changes, if appropriate? This action should be done after your changes are approved but not merged.
- [ ] Type Labels       Select github labels for the type of this change: bug, enhancement, etc.
- [ ] Product Labels    Select github labels for the product affected: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

2023-12-07 21:47 UTC, dthain commented
So, as far as I can tell:
- A library task will get two pipes created, which are noted on the command line.
- All tasks get the same stdin/stdout/stderr handling.
- A function call will get an output file created in the task sandbox, but it won't write anything there because any printfs in the library will go to the library's stdout instead.

Is that correct?

Now, conceivably, we could have the library main loop re-open its stdout/err to write to the function call tasks' stdout instead, after the fork in library_network_code.py.  That way, any output specific to the function call would come back with the function call itself.

Good idea or bad idea?

2023-12-08 14:48 UTC, tphung3 commented
Yes to points 1 and 2. For point 3, the function call writes the result to its output file once it's done, but its stdout/err are not captured like other tasks.

2023-12-08 17:31 UTC, tphung3 commented
The new change should capture stdout/err of the library task and the function call in two separate places.

2023-12-08 17:46 UTC, dthain requested changes
This seems like a nice simplification of file handling in general.
1 - Please bump the VINE_PROTOCOL number, since this would break compatibility with prior managers.
2 - Do we need to update the corresponding library network code used in parsl, or is that generated automatically?

2023-12-08 17:54 UTC, tphung3 commented
1) Do you mean this line? https://github.com/cooperative-computing-lab/cctools/blob/7d5cf463a4175330335c91a54b31860a9da5b444/taskvine/src/manager/vine_protocol.h#L16

2) The network code is generated automatically from poncho network code.

2023-12-09 18:14 UTC, dthain approved these changes

2023-12-09 18:15 UTC, merged