Vine rc unlink files
cooperative-computing-lab/cctools pull request #3612
Opened 2024-01-23 19:22 UTC by btovar

## Proposed changes

Adds the VINE_UNLINK_ON_RC0 flag to delete files from disk when the reference count goes to 0.
Intended only for internal taskvine usage.

## Post-change actions

Put an 'x' in the boxes that describe post-change actions that you have done.
The more 'x' ticked, the faster your changes are accepted by maintainers.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Did you update the manual to reflect your changes, if appropriate? This action should be done after your changes are approved but not merged.
- [ ] Type Labels       Select github labels for the type of this change: bug, enhancement, etc.
- [ ] Product Labels    Select github labels for the product affected: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

## Additional comments
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to start the ball rolling.

2024-01-23 19:48 UTC, dthain requested changes
Yes, I think this is the right idea. 
1 - I am comfortable making this a user-visible feature, since I think this situation is come to come up again in the future.  Trying to think of names that make sense to the end user.  Maybe `UNLINK_WHEN_DONE`?  I'm open to ideas here.
2 - Add a `debug` when the file is actually unlinked, since that will have some non-trivial cost, and we want to know when it happens.

2024-01-23 20:21 UTC, dthain commented
I'm thinking `DONE` is nice because it's actually vague about when that happens, but makes it clear the user is giving the responsibility over to the manager...

2024-01-23 20:47 UTC, dthain commented
This makes sense to me, does it solve the problem with Connor's app?

2024-01-23 21:14 UTC, dthain approved these changes

2024-01-23 21:24 UTC, btovar commented
I'm testing it... Now it is a matter of getting the logic in the dag right when adding the checkpoints.

2024-01-25 21:08 UTC, dthain commented
RTM?

2024-01-31 16:07 UTC, btovar commented
Splitting into several prs.

2024-01-31 16:07 UTC, closed without merging