Vine: Recover temp files on worker removal
cooperative-computing-lab/cctools pull request #3744
Opened 2024-03-25 00:08 UTC by cboumalh

## Proposed changes

Please describe your changes (e.g., what problems they attempt to solve, what results are expected, etc.) Additional motivation and context are welcome.
Please also mention relevant issues and pull requests as appropriate.

## Post-change actions

Put an 'x' in the boxes that describe post-change actions that you have done.
The more 'x' ticked, the faster your changes are accepted by maintainers.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Did you update the manual to reflect your changes, if appropriate? This action should be done after your changes are approved but not merged.
- [ ] Type Labels       Select github labels for the type of this change: bug, enhancement, etc.
- [ ] Product Labels    Select github labels for the product affected: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

## Additional comments
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to start the ball rolling.

2024-03-25 13:37 UTC, dthain requested changes
This is on the right track, just a few code cleanups, please.

2024-03-25 13:37 UTC, dthain commented on taskvine/src/manager/vine_current_transfers.c
> +int vine_current_file_worker_receiving(struct vine_manager *q, struct vine_worker_info *w, const char *cachename)
Must be called `vine_current_transfers_` something because it is a public member of `vine_current_transfers.h`

2024-03-25 13:37 UTC, dthain commented on taskvine/src/manager/vine_current_transfers.h
> +int vine_current_file_worker_receiving(struct vine_manager *q, struct vine_worker_info *w, const char *cachename);
Ibid

2024-03-25 13:37 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> +	recover_worker_temp_files(q, w);
Make this contingent on an option that can be set with `vine_tune`.
We ware going to compare various options for recovery and you will want to control them from the outside.

2024-03-25 13:37 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> +				set_remove(workers, w);
This code seems to duplicate what's going on in `vine_file_replica_table_remove`, please make use of that function.

2024-03-27 22:26 UTC, colinthomas-z80 requested changes

2024-03-27 22:26 UTC, colinthomas-z80 commented on taskvine/src/manager/vine_file_replica_table.c
> +// remove a file from the file worker table.
Doesn't this really remove a "worker" from the file worker table

2024-03-27 22:26 UTC, colinthomas-z80 commented on taskvine/src/manager/vine_manager.c
> +	} else if (!strcmp(name, "transfer_temps_recovery")) {
use hyphen in the vine_tune parameter: "transfer-temps-recovery"

2024-03-27 22:27 UTC, colinthomas-z80 commented on taskvine/src/manager/vine_manager.c
> +	} else if (!strcmp(name, "transfer_temps_recovery")) {
also update `cctools/doc/manuals/taskvine/index.md` with the new parameter

2024-03-28 11:57 UTC, btovar requested changes

2024-03-28 11:57 UTC, btovar commented on taskvine/src/manager/vine_current_transfers.c
> +int vine_current_transfers_file_worker_recv(struct vine_manager *q, struct vine_worker_info *w, const char *cachename)
I think the pr may be out of date. Current master has a similar function.

2024-03-28 11:57 UTC, btovar commented on taskvine/src/manager/vine_file_replica_table.c
> +	return workers ? set_size(workers) : 0;
I don't recommend doing this. The returned value should correspond to what the function does. In this case, returning the number of replicas that still exists does not make sense for the function. I'd leave `vine_file_worker_table_remove` as it was, remove `vine_file_worker_table_remove` as removing a replica should always update the corresponding worker and there is no sense of having a second function.

Then in `recover_temp_files` delete the replica and check whether there are still replicas.

2024-04-08 12:13 UTC, btovar requested changes

2024-04-08 12:13 UTC, btovar commented on taskvine/src/manager/vine_current_transfers.c
> +	HASH_TABLE_ITERATE(q->current_transfer_table, id, t)
This is inefficient. Instead check if worker is in the value of the table m->file_worker_table. See `vine_file_replica_table_insert`.

2024-04-17 19:02 UTC, dthain requested changes
This is looking good, just a few minor things.

2024-04-17 19:02 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> +static void recover_worker_temp_files(struct vine_manager *q, struct vine_worker_info *w)
This function doesn't actually do the recovery, so let's call it something like `remember_lost_temp_files` or something along those lines.

2024-04-17 19:02 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> +	hash_table_delete(q->temp_files_to_repilicate);
Also `hash_table_clear(table,0)` to get rid of any remaining entries.

2024-04-22 11:55 UTC, btovar approved these changes

2024-04-22 11:56 UTC, merged