Vine: Thread Controller for FunctionCalls
cooperative-computing-lab/cctools pull request #3764
Opened 2024-04-14 00:28 UTC by JinZhou5042

## Proposed changes

A lightweight thread resource controller for FunctionCall tasks, adopted from [threadpoolctl](https://github.com/joblib/threadpoolctl) but more compact, with the minimum overhead to manage thread numbers at runtime.

## Post-change actions

Put an 'x' in the boxes that describe post-change actions that you have done.
The more 'x' ticked, the faster your changes are accepted by maintainers.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Did you update the manual to reflect your changes, if appropriate? This action should be done after your changes are approved but not merged.
- [ ] Type Labels       Select github labels for the type of this change: bug, enhancement, etc.
- [ ] Product Labels    Select github labels for the product affected: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

## Additional comments
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to start the ball rolling.

2024-04-15 13:20 UTC, btovar requested changes

2024-04-15 13:20 UTC, btovar commented on poncho/src/poncho/library_network_code.py
> +    class CLibController:
Add comment to give attribution to original implementation.

2024-04-15 13:20 UTC, btovar commented on poncho/src/poncho/library_network_code.py
> +            with ThreadpoolLimits(limits=library_cores // function_slots):
Add comment to give attribution to original implementation.

2024-04-16 21:47 UTC, JinZhou5042 commented
The adopted little thread pool controller involves more variations of mathematical packages on the C site compared to `threadpoolctl`, including _flexiblas_, _mkl_core_, _libmkl_rt_, _gomp_, _iomp5_, _libiomp5_, _libomp_ and _vcomp140_, which may prevent core over-commitment under some unexpected conditions. And we can simply update it by inserting a couple of lines once detecting some un-configured libraries. 

However, directly importing the original package is easier and it makes the library code more compact. I think either is fine, how do you think @btovar

2024-04-17 15:59 UTC, dthain commented
@colinthomas-z80 what are you thoughts on how this affects the Parsl install?  While we strongly encourage Conda installs, I believe that their CI builds download our tarball and then do some `pip`.

2024-04-17 16:19 UTC, colinthomas-z80 commented
@dthain I'm not sure what the issue is exactly? these new imports are part of the standard library I believe

2024-04-22 03:59 UTC, closed without merging