TaskVine: Fix logging of library deployment
cooperative-computing-lab/cctools pull request #3780
Opened 2024-04-24 14:51 UTC by tphung3

## Proposed changes

Previously whenever a function call is about to be dispatched, the manager writes `VINE_LIBRARY_SENT` to the transaction log which is incorrect. This is fixed so that the manager only writes it when a library is about to be dispatched.

Also finding the library in `commit_task_to_worker()` is redundant as `t->library_task` is set in vine_manager_check_worker_can_run_function_task()`, so it is removed.

## Post-change actions

Put an 'x' in the boxes that describe post-change actions that you have done.
The more 'x' ticked, the faster your changes are accepted by maintainers.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Did you update the manual to reflect your changes, if appropriate? This action should be done after your changes are approved but not merged.
- [ ] Type Labels       Select github labels for the type of this change: bug, enhancement, etc.
- [ ] Product Labels    Select github labels for the product affected: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

## Additional comments
This section is dedicated to changes that are ambitious or complex and require substantial discussions. Feel free to start the ball rolling.

2024-04-24 15:31 UTC, dthain requested changes
Hmm, although this is a simple change, I think you should split it into two PRs.

Changing the library update message is obviously correct.

It's not so obvious to me that removing `find_library_on_worker_for_task` is correct.

2024-04-24 15:55 UTC, BarrySlyDelgado commented
I think `find_library_on_worker_for_task` was put there as `check_worker_can_run_function_task` would set the function call's worker for each worker we checked during scheduling. I.e. the worker with the library_task we last checked that could run the function call would be set as the function_call's worker rather than the worker we return during scheduling, like in `find_worker_by_files`.

2024-04-25 12:32 UTC, dthain approved these changes

2024-04-30 17:08 UTC, dthain approved these changes

2024-04-30 17:08 UTC, merged