vine: prune stale files in daskvine
cooperative-computing-lab/cctools pull request #3880
Opened 2024-07-16 17:50 UTC by JinZhou5042

## Proposed Changes

Give an overall description of the changes, along with the context and motivation.
Mention relevant issues and pull requests as needed.

## Merge Checklist

The following items must be completed before PRs can be merge.
Check these off to verify you have completed all steps.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Update the manual to reflect user-visible changes.
- [ ] Type Labels       Select a github label for the type: bugfix, enhancement, etc.
- [ ] Product Labels    Select a github label for the product: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

2024-07-16 18:54 UTC, JinZhou5042 commented
I don't quite get the reason why I fail on the ` build-conda-linux (pull_request)` part...

2024-07-16 18:57 UTC, JinZhou5042 commented
evaluation at a larger scale

with 200 workers, before pruning
![worker_disk_usage](https://github.com/user-attachments/assets/933a06e7-a32f-47a4-b060-f4902cb04792)

with 117 workers, after pruning
![worker_disk_usage (1)](https://github.com/user-attachments/assets/a8e3ccfb-cbc1-4c34-a25e-23cc13b6c110)

2024-07-17 12:49 UTC, btovar commented
This looks awesome!

2024-07-17 13:05 UTC, btovar requested changes

2024-07-17 13:05 UTC, btovar commented on taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
> +                        children = dag.get_children(t.key)
Move this code to a method, like `DaskVine.prune_cluster` or something like that.

2024-07-17 13:05 UTC, btovar commented on taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
> +        self.inputs = []
I don't think this is needed.

2024-07-17 13:11 UTC, btovar commented
The failure in the CI is unrelated to your pr. Submitting a fix shortly.

2024-07-17 16:33 UTC, btovar approved these changes

2024-07-17 16:33 UTC, btovar commented
Ready to merge?

2024-07-17 16:37 UTC, JinZhou5042 commented
RTM

2024-07-17 16:39 UTC, btovar commented
Actually before merging, could you add an option to `DaskVine.get` called `prune_files` so that users can turn on/off this facility? The default should be False (not to prune), as that is the current behavior.

2024-07-17 16:50 UTC, JinZhou5042 commented
Absoulutely!

2024-07-17 17:57 UTC, JinZhou5042 commented
RTM if you think it's good.

2024-07-17 18:33 UTC, btovar requested changes

2024-07-17 18:33 UTC, btovar commented on taskvine/src/bindings/python3/ndcctools/taskvine/dask_executor.py
> +            prune_cluster=False,
Let's call it `prune_files`.  I don't think that we explain the term `cluster` in the taskvine documentation, etc.

2024-07-18 13:43 UTC, btovar approved these changes
nice, thanks!

2024-07-18 13:44 UTC, merged