dttools: priority queue data structure
cooperative-computing-lab/cctools pull request #3915
Opened 2024-08-12 17:53 UTC by JinZhou5042

## Proposed Changes

Give an overall description of the changes, along with the context and motivation.
Mention relevant issues and pull requests as needed.

## Merge Checklist

The following items must be completed before PRs can be merge.
Check these off to verify you have completed all steps.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Update the manual to reflect user-visible changes.
- [ ] Type Labels       Select a github label for the type: bugfix, enhancement, etc.
- [ ] Product Labels    Select a github label for the product: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

2024-08-12 19:13 UTC, dthain requested changes
I like this implementation, it's nice and straightforward.

A few nits about the API documentation versus comments in the implementation below.

Now, the real question is, can it be worked into our various scheduling methods without breaking everything?  Make sure you talk to @colinthomas-z80 about how/why we iterate over only part of the list at one time.

2024-08-12 19:13 UTC, dthain commented on dttools/src/priority_queue.h
> +can be accessed in constant time.
Is that the only guarantee offered here, or does it also guarantee that iteration is performed in order?

2024-08-12 19:13 UTC, dthain commented on dttools/src/priority_queue.h
> +The 0th element is used as a sentinel with the highest priority to simplify boundary checks in heap operations like swim and sink.
Is that a detail visible to the user of the structure, or just an implementation detail?

If it is visible, then you should probably say something about it in pop, iterate, etc.

If not, then move the comment to a good place in the .c file.

2024-08-12 19:13 UTC, dthain commented on dttools/src/priority_queue.h
> +function @ref swim is called to maintain the heap property.
Same issue here, does the caller of this API call sink and swim?

2024-08-12 19:32 UTC, colinthomas-z80 commented
I was thinking this could possibly replace the list rotation and the way we only visit a subset of the tasks each scheduling attempt. 

As long as the priority includes whether the task is ready to run or not, i.e. data dependencies are present. We should be finding a good task without looking too deep in the list.

2024-08-12 20:03 UTC, JinZhou5042 commented
When all tasks have the same priority, the queue might look like this (priority, data):

```
[(1, "a"), (1, "b"), (1, "c"), (1, "d"), (1, "e")]
```
The first time to pop, we get `(1, "a")`. If we decide this isn't the element we need right now and want to consider it later, we push it back into the queue, resulting in:

```
[(1, "b"), (1, "c"), (1, "d"), (1, "e"), (1, "a")]
```

This is essentially like rotating the list.

In contrast, when tasks have different priorities, the element with the highest priority will stay at the top of the queue if we repeatedly pop and push it. For example, with this priority queue: (the store order is specified [here](https://github.com/cooperative-computing-lab/cctools/pull/3915/files#diff-5f8531ebe6023b33854d3806e6a6385db3b8c9d07f9e260e54f63b40725b4241R35)):
```
[(5, "e"), (4, "d"), (2, "b"), (1, "a"), (3, "c")]
```
Popping the first element and then deciding to reconsider it later would place it back at the top of the queue, since its priority remains unchanged.

However, in real-world scenarios, if an element is popped and set aside for later consideration, it probably shouldn't retain its high priority. Instead, we might decrease its priority by 1 or set it to the lowest priority, allowing other elements deeper in the queue a fair chance to be considered.

2024-08-12 20:10 UTC, JinZhou5042 commented
What I'm uncertain about is that using a priority queue instead of a normal list to store ready tasks will eliminate the opportunity of scheduling tasks using a breadth-first approach (implementing FIFO in a priority is quite expensive, with the complexity of `O(n^2)`). 

Additionally, considering the use of a tuning parameter to determine which data structure to use might increase the complexity.

2024-08-13 20:34 UTC, JinZhou5042 commented
I did a quick experiment with the script provided by Colin:
``` Python
#! /usr/bin/env python

import argparse
import sys
import time
import math
import ndcctools.taskvine as tv
import random

if __name__ == '__main__':
    q = tv.Manager(port=9123)

    satisfied = False

    # initial task count
    t_count = 5000

    print(f"Submitting {t_count} tasks")
    t_start = time.time()
   
    for i in range(t_count):
        t = tv.Task(":")
        q.submit(t
    
    t_submitted = time.time()
    print(f"Time to submit {t_submitted-t_start}s : {t_count*4/(t_submitted-t_start)} tasks per second.") 

    while not q.empty():
        t = q.wait(5)

    t_end = time.time()

    complete = t_end - t_start

    print(f"Tasks completed in {complete}s : {t_count/(complete)} tasks per second.")
    print()
    
    quit()
```

As mentioned by @colinthomas-z80, the reason to introduce list rotation is that in the manager end, it first scans the task ready list, to see if there are any tasks available to be scheduled, and then collects results that are ready on the worker. But, if there are no workers available, it still scans the whole ready list and see if it can schedule another.

The solution is to only consider a small number of tasks each attempt, say 100. The looking through process will eventually break out it has scanned 100 tasks. However, the consequence of looking at only 100 tasks is that tasks deeper in the ready list are not treated with a fair chance to be scheduled. So list rotation is introduced, for the purpose of wrapping around everything as it proceeds.

2024-08-13 20:37 UTC, JinZhou5042 commented
I ran on 1 worker with 16 cores with three configurations, list without rotation, list with rotation and priority queue (every task has the same priority), the priority queue seems to have pretty much the same performance when compared to rotation list.
<img width="632" alt="image" src="https://github.com/user-attachments/assets/c5958417-5b4d-4f0a-ba2c-112278d61cee">

2024-08-13 20:59 UTC, colinthomas-z80 commented
I’m not sure why there is so much variability in the results. Can you see if things change if you run your worker with a finite disk value, such as `—disk 100` ? You may be experiencing the ongoing disk issue

2024-08-13 21:10 UTC, JinZhou5042 commented
Ah, I set with finite values to disk and memory and the variability issue immediately disappears.

2024-08-13 21:28 UTC, JinZhou5042 commented
The updated results

<img width="599" alt="image" src="https://github.com/user-attachments/assets/983fe0ed-58da-4683-bdde-49a2bc82fb0f">

2024-08-14 19:15 UTC, JinZhou5042 commented
Do we want to fully replace the list with a priority queue, or use a heuristic?

2024-08-14 19:21 UTC, dthain commented
Jin, your question is too vague to be answered.

If you are proposing to replace the list with a priority queue, then you need to show us the changes needed in taskvine to use the new data structure.  And we have to consider carefully whether it meets all of our needs.

I don't know what you mean by "a heuristic".  Do you have a specific heuristic in mind?

2024-08-14 19:28 UTC, JinZhou5042 commented
Well, I can propose a temporary PR quickly to show what are the changes to replace the list with a priority queue after this one is merged. 

I don't know if it is a heuristic approach, but we can support both data structures and let the users make the decision which one they want to use. By default, they are using the link list, but if they want to specify some tasks with different priorities, they can tune a parameter like `m.tune('priority_task_mode', 1)` to manually switch it on.

2024-08-20 15:20 UTC, closed without merging