Hungry feature
cooperative-computing-lab/cctools pull request #3949
Opened 2024-10-03 18:26 UTC by RamenMode

## Proposed Changes

Give an overall description of the changes, along with the context and motivation.
Mention relevant issues and pull requests as needed.

Changes 

## Merge Checklist

The following items must be completed before PRs can be merge.
Check these off to verify you have completed all steps.

- [X] `make test`       Run local tests prior to pushing.
- [X] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [X] `make lint`       Run lint on source code prior to pushing.
- [X] Manual Update     Update the manual to reflect user-visible changes.
- [X] Type Labels       Select a github label for the type: bugfix, enhancement, etc.
- [X] Product Labels    Select a github label for the product: TaskVine, Makeflow, etc.
- [X] PR RTM            Mark your PR as ready to merge.

2024-10-08 18:07 UTC, dthain requested changes
Overall, the right idea, see fixes -

2024-10-08 18:07 UTC, dthain commented on taskvine/src/manager/.vscode/c_cpp_properties.json
> +{
Don't include this file.

2024-10-08 18:07 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> +	while (i > 0) {
Use LIST_ITERATE here.

2024-10-10 18:34 UTC, RamenMode commented on taskvine/src/manager/vine_manager.c
> +	while (i > 0) {
changed

2024-10-10 18:34 UTC, RamenMode commented on taskvine/src/manager/.vscode/c_cpp_properties.json
> +{
changed

2024-10-10 18:34 UTC, RamenMode commented
Made the necessary changes

2024-10-15 15:03 UTC, dthain approved these changes

2024-10-15 15:03 UTC, merged