vine: handling temp files when peer transfers disabled
cooperative-computing-lab/cctools pull request #3964
Opened 2024-10-30 16:00 UTC by colinthomas-z80

## Proposed Changes

Give an overall description of the changes, along with the context and motivation.
Mention relevant issues and pull requests as needed.

## Merge Checklist

The following items must be completed before PRs can be merge.
Check these off to verify you have completed all steps.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Update the manual to reflect user-visible changes.
- [ ] Type Labels       Select a github label for the type: bugfix, enhancement, etc.
- [ ] Product Labels    Select a github label for the product: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

2024-11-01 15:04 UTC, btovar requested changes

2024-11-01 15:04 UTC, btovar commented on taskvine/src/manager/vine_file.c
> +	return vine_file_create("temp", 0, 0, 0, VINE_FILE, 0, cache, 0);
I'm not quite sure this one will work. Wouldn't all the temp files get the same name locally at the manager? Also I suggest changing the name to `vine_file_temp_no_peers` or something like that.

2024-11-01 15:12 UTC, colinthomas-z80 commented
I am thinking about how to add a mechanism to clean up these local temp files when the workflow completes, to make them similar in function to real temp files

2024-11-01 15:36 UTC, dthain commented
https://cctools.readthedocs.io/en/latest/api/html/taskvine_8h.html#a2d4d0d4621e65083488ccef6464f334ca898d527e82997c21744baf54409cce36

2024-11-05 14:44 UTC, dthain commented
This would seem to give all temp files from the same user the same name.
```
char *name = string_format("temp-local-%u", uid);
```
Am I missing something?

2024-11-05 14:52 UTC, colinthomas-z80 commented
You are right. I was mistaken about uid vs. uuid behavior

2024-11-05 19:05 UTC, dthain approved these changes

2024-11-05 19:05 UTC, merged