WIP: Add Robust Error Checking to Library and Worker's Communications
cooperative-computing-lab/cctools pull request #3974
Opened 2024-11-06 21:55 UTC by tphung3

## Proposed Changes

Give an overall description of the changes, along with the context and motivation.
Mention relevant issues and pull requests as needed.

## Merge Checklist

The following items must be completed before PRs can be merge.
Check these off to verify you have completed all steps.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Update the manual to reflect user-visible changes.
- [ ] Type Labels       Select a github label for the type: bugfix, enhancement, etc.
- [ ] Product Labels    Select a github label for the product: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

2024-11-08 20:59 UTC, dthain requested changes

2024-11-18 14:54 UTC, btovar requested changes

2024-11-18 14:54 UTC, btovar commented on taskvine/src/manager/vine_manager.c
> +	int n = sscanf(line, "taskvine %d %d %s %s %s %s", &worker_protocol, &worker_library_protocol, items[0], items[1], items[2], items[3]);
I'm not sure about having a different number for the library protocol.  I'd keep only the worker_protocol and increment it if the library communication between the worker and library changes.

2024-11-18 14:54 UTC, btovar commented on taskvine/src/manager/vine_protocol.h
> +#define VINE_LIBRARY_PROTOCOL_VERSION 1
See above, this sounds like an over complication.

2024-11-21 18:53 UTC, btovar approved these changes

2024-11-21 18:53 UTC, btovar commented
ready to merge?

2024-11-21 19:57 UTC, tphung3 commented
Yep. It's RTM.

2024-11-22 13:58 UTC, merged