Create batch_queue_flux stub
cooperative-computing-lab/cctools pull request #3978
Opened 2024-11-12 20:55 UTC by dblitt

## Proposed Changes

This PR creates a stub batch_queue module for the [Flux Framework](https://flux-framework.org/). I will be working in the immediate future to implement the submit, wait, and remove functionality of this module so Makeflow and vine_factory will be able to natively submit jobs to a flux instance.

I also have fixed some out of date documentation in `batch_queue.h`

## Merge Checklist

The following items must be completed before PRs can be merge.
Check these off to verify you have completed all steps.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update     Update the manual to reflect user-visible changes.
- [ ] Type Labels       Select a github label for the type: bugfix, enhancement, etc.
- [ ] Product Labels    Select a github label for the product: TaskVine, Makeflow, etc.
- [ ] PR RTM            Mark your PR as ready to merge.

2024-11-13 20:25 UTC, tphung3 commented
Ok, this is a good template for further work. I think you know Flux enough by now to implement `batch_queue_flux_submit` and `batch_queue_flux_remove`. Don't worry about supporting all features, and instead try to submit basic Linux commands to flux and remove them using above APIs. To test your work you can write a custom test script calling `batch_queue_flux_submit` and `batch_queue_flux_remove`.

2024-12-02 22:20 UTC, dblitt commented
@tphung3 @dthain I've pushed the implementation for {submit,wait,remove}

2024-12-05 15:03 UTC, tphung3 requested changes

2024-12-05 17:45 UTC, dthain commented
Per our previous discussion, it is ok to assume that the flux executor makes use of a shared filesystem, and it is not necessary to transfer files back and forth.  (That is also the general assumption of the "cluster" module)

2024-12-12 18:04 UTC, dblitt commented on batch_job/src/batch_queue_flux.c
> +	// Flux does not support staging files out of the worker environment, so warn for each file
Yes, this requires further investigation. I think it has to do with the location of the working directory the worker node is placed into

2024-12-12 18:08 UTC, dblitt commented on batch_job/src/batch_queue_flux.c
> +			while (fread(buffer, sizeof(char), sizeof(buffer) / sizeof(char), archive_create_pipe) > 0) {
Here we are just using buffer as a dumping ground to flush out all output from the popen pipe. I've added a memset to 0 later in the file when we reuse buffer as r/w.

2024-12-13 03:01 UTC, tphung3 commented on batch_job/src/batch_queue_flux.c
> +		LIST_ITERATE(bt->input_files, bf)
Any reason why line 114 is not `LIST_ITERATE(bt->output_files, bf)`?

2024-12-13 03:02 UTC, tphung3 commented on batch_job/src/batch_queue_flux.c
> +		LIST_ITERATE(bt->input_files, bf)
never mind, I checked the wrong code :)

2024-12-13 15:00 UTC, dthain commented on batch_job/src/batch_queue_flux.c
> +	// Flux does not support staging files out of the worker environment, so warn for each file
`batch_queue_condor` actually does stage out files.  In HTCondor, all files created in the sandbox are sent back to the submitter, it isn't necessary to name them individually.

2024-12-13 15:01 UTC, dthain commented
This is looking pretty good overall, can you please add a suitable paragraph to the makeflow manual describing the module?

2024-12-19 16:03 UTC, dthain approved these changes

2024-12-19 16:03 UTC, dthain commented
@tphung3 any other concerns?

2025-01-10 15:43 UTC, dthain approved these changes

2025-01-10 15:44 UTC, merged