Vine: Add IO test for function calls
cooperative-computing-lab/cctools pull request #3981
Opened 2024-11-14 16:49 UTC by tphung3

## Proposed Changes

This PR adds an IO test (input/output staging) for function calls.

## Merge Checklist

The following items must be completed before PRs can be merged.
Check these off to verify you have completed all steps.

- [x] `make test`       Run local tests prior to pushing.
- [x] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [x] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update:     Update the manual to reflect user-visible changes.
- [x] Type Labels:       Select a github label for the type: bugfix, enhancement, etc.
- [x] Product Labels:    Select a github label for the product: TaskVine, Makeflow, etc.
- [x] PR RTM:            Mark your PR as ready to merge.

2024-11-14 17:00 UTC, tphung3 commented
@btovar I added the IO test for function calls here and they seem to work as intended. Maybe we need a test where a function call should fail when a file isn't brought back?

2024-11-18 15:05 UTC, btovar requested changes

2024-11-18 15:05 UTC, btovar commented on taskvine/test/TR_vine_python_serverless.sh
> +TEST_FILE=vine_python_serverless.py
I'd recommend against naming this variable `TEST_FILE`. It gives the impression that the file can be removed. Use PYTHON_SCRIPT?

2024-11-21 18:51 UTC, btovar approved these changes

2024-11-21 18:52 UTC, btovar commented
ready to merge?

2024-11-21 19:57 UTC, tphung3 commented
It's RTM.

2024-11-22 13:58 UTC, merged