vine: efficient resource allocation
cooperative-computing-lab/cctools pull request #4006
Opened 2024-12-11 02:22 UTC by JinZhou5042

## Proposed Changes

Give an overall description of the changes, along with the context and motivation.
Mention relevant issues and pull requests as needed.

## Merge Checklist

The following items must be completed before PRs can be merged.
Check these off to verify you have completed all steps.

- [ ] `make test`       Run local tests prior to pushing.
- [ ] `make format`     Format source code to comply with lint policies. Note that some lint errors can only be resolved manually (e.g., Python)
- [ ] `make lint`       Run lint on source code prior to pushing.
- [ ] Manual Update:     Update the manual to reflect user-visible changes.
- [ ] Type Labels:       Select a github label for the type: bugfix, enhancement, etc.
- [ ] Product Labels:    Select a github label for the product: TaskVine, Makeflow, etc.
- [ ] PR RTM:            Mark your PR as ready to merge.

2024-12-12 22:19 UTC, JinZhou5042 commented
Before @colinthomas-z80 's comment, I didn't fully understand the problem from the perspective of algorithm design, the math was straightforward but didn't identify the underlying problem. 

What's going wrong in the code is that we are using `disk_total - cache_inuse` as the available disk to allocate. However, that's not the actual amount of available disk to use. Instead, the total size of task sandboxes should be accounted as well, which means the available disk should be: `disk_total - cache_inuse - sandboxes`.

That said, we should use `task_disk_estimate = (disk_total - disk_inuse) / proportion` to guess the disk allocation. @dthain further suggested that for the disk estimate, leaving half of it being freed would provide more disk space for incoming tasks and allow for potential cache expansion, so we have `task_disk_estimate /= 2`.

With these changes, results are very encouraging! Both concurrency and success rate for resource estimate improved significantly, and the policy is very self-consistent!

2024-12-13 01:22 UTC, btovar commented
Jin,  I don't think that `disk_total - cache_inuse - sandboxes` is correct. One way to see this is that if the tasks do not have any input files, and I want to schedule two tasks to the worker, the second task will get a smaller proportion than the first one.

I believe that cache_inuse and sandboxes are not important here and are just confusing the main issue, which is that by design, the proportional computation gives conservative allocations. This is true for all the resources, and it is my hunch that this is not an accounting problem.

I'd be more comfortable with a solution that includes all the resources. For example, check at the end if an allocation from a computed proportion would not fit in the worker, then modify it in an easy-to-explain way (e.g., divide it by 2), and let the scheduler decide if it would fit, and maybe reject the allocation. I do not think we want to allocate whatever is left, as we want automated allocations for similar tasks to be similar (about the same order of magnitude). For example, we do not want one task to be 1GB and another to be 10MB just because that's what was left.

2024-12-13 17:14 UTC, btovar commented on taskvine/src/manager/vine_manager.c
> +			q->total_available_cores += (total - w->resources->cores.total);
Or we could update the count of cores every time a worker sends a resource update / disconnects.

2024-12-13 17:15 UTC, btovar commented on taskvine/src/manager/vine_manager.c
> -	if (t->input_files_size > 0) {
We need this `if`.  `input_files_size` is -1 when unset, so you do not want to -(-1) = +1 a MB to the available disk.

2024-12-13 17:19 UTC, btovar commented on taskvine/src/manager/vine_manager.c
> +			limits->cores = MIN(limits->cores, cores_available);
As discussed, we may only want to update the proportion when it is larger than the *_available, then only update it to  allocated/2.  If that would not fit in *_available, that's ok.  We don't want a tasks to end up with 1MB of memory/disk.

2024-12-13 22:28 UTC, JinZhou5042 commented
What is the purpose for `min` and `min_proportion`? I think `max` and `max_proportion` are used throughout the way.

2024-12-14 13:56 UTC, btovar commented
The are two kinds of resource specifications for a task. “max resources” specifies a hard limit on the resources that the task can use. “min resources” indicates the minimum of resources that a task needs to even fit the worker. In almost every case, “max resources” is the resource specification used to determine how many resources to allocate.
“min resources” comes into play when:

-	They are specified explicitly by the user through the task categories.
-	There is an observed sandbox size for a task category.
-	The automatic allocation modes have not determined yet a “max resource” allocation, but they have enough information to know that an allocation size won’t be enough for the task.

 In the code, max_proportion computes the proportional resources using “max resources,” while min_proportion does the same for “min resources.” Then there is a check that forces max_proportion to be at least min_proportion. Here is a case when this check comes into play when using the resource monitor: (It is similar for disk without the resource monitor, but you have to take into account the cache, which makes the example less clear.)

-	The worker has  10 cores and 10GB of memory.
-	The task states that it uses 1 core, either through explicit value by user, or automatic allocation by the category code.
-	Because of proportion, tasks run with 1 core and 1 GB of memory.
-	The resource monitor kills the task as the usage went to 3GB of memory.
-	When the task is to be scheduled again, max_proportion will say to use 1 core and 1 GB of memory, but min_proportion will say at least  ceiling(10/3) = 4GB of memory, which turns into 5GB if the “fit an integer number of tasks” switch is activated (this is the default). Thus, the minimum allocation would be 5 cores and 5GB of memory. This is larger than the max proportion, so it is used instead. This proportion is used for disk too, as appropriate.
-	Finally, the 5 cores allocated may be revised again. If the 1 core value was set explicitly by the user, then the limit is set to 1 core. If the limit came from automatic allocations, then we use the 5 cores value.

2024-12-14 21:20 UTC, JinZhou5042 commented
@btovar Thanks Ben, that was very clear!

2024-12-20 04:00 UTC, JinZhou5042 commented
Just a reminder, there was a temporary hack in #3913 in order to let Greg's application to run, but I forgot about it after that. However, that may cause potential issues for the library/function task executions. This PR mainly improves resource allocations for regular python tasks. We will discuss about the case for library/function tasks after the break and I will make another PR to fix that hack!

2025-01-14 20:10 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> +		itable_remove(q->running_library_instances, t->task_id);
It makes sense to have a running library table.

But let's put this down at line 617 to keep all the core data structure changes together.

(`itable_remove` will be a no-op if it is not a library task.)

2025-01-14 20:10 UTC, dthain commented on taskvine/src/manager/vine_manager.c
>  		printf("Library %s failed on worker %s (%s)", t->provides_library, w->hostname, w->addrport);
Use `debug(D_VINE|D_NOTICE)` to have consistent handling of messages to the user.  (It will also go to the log file)

2025-01-14 20:10 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> +	/* Shortcut if the task explicitly requests all resources */
This is a large rework of a critical function, can you explain in more detail what this accomplishes?

2025-01-14 20:10 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> +		char *local_library_log_filename = string_format("library-%d.debug.log", q->next_library_id++);
Hmm, I think this will be confusing because the library ids don't look any different than task ids.

How about just use the task_id in the name of the debug file?

That will make it easy to align library debug file names with other events about that library task in the manager's debug log.

2025-01-16 16:13 UTC, dthain commented
Come on over today and let's talk through a few things that I would like to understand better.

2025-01-16 16:43 UTC, dthain commented on taskvine/src/manager/vine_schedule.c
> +	/* Skip if it is a function task */
More detailed comment here that compatibility was checked elsewhere.

2025-01-17 16:20 UTC, dthain commented
Per our discussion today, the disk allocation should be:
```
disk = ((total - cache)*frac)/proportion
```
Where `frac` is a tunable value with a default of 0.75

2025-01-17 17:31 UTC, btovar commented on taskvine/src/manager/vine_manager.c
> +	q->disk_allocation_throttle_factor = 0.75;
`disk_proportion_available_to_task = 0.75` ?

2025-01-17 19:05 UTC, dthain requested changes
One last thing, almost there!

2025-01-17 19:05 UTC, dthain commented on taskvine/src/manager/vine_manager.c
> +	} else if (!strcmp(name, "disk-allocation-throttle-factor")) {
Fix name to match variable!

2025-01-17 19:36 UTC, dthain approved these changes
Hooray!  Good work on a long and complex PR!

2025-01-21 16:05 UTC, btovar requested changes
There seem to be a lot of changes in this pr that are unrelated.
I suggest to close this pr and resubmit with only the following changes:
- The multiplying factor to the disk_available.
- The corresponding tune parameter.
- Updates to the tune parameter documentation in the manual.

2025-01-21 16:05 UTC, btovar commented on taskvine/src/manager/vine_manager.c
> -		double min_proportion = -1;
Min proportion is needed when using automatic resource allocation via categories, please do not remove it.

2025-01-21 16:40 UTC, dthain commented
Hmm, are you able to run a test by going back to an earlier version of Coffea and/or DV5?

2025-01-21 16:52 UTC, JinZhou5042 commented
Just in case something unexpected happens since we had a few PRs getting merged. I can test with an earlier version of Dask + DaskVine in my end, but if try to merge that PR then resource allocations for the latest cctools will remain untested.

2025-01-27 19:08 UTC, closed without merging

2025-01-27 19:08 UTC, JinZhou5042 commented
All features in this PR have been separated into a sequence of PRs.